<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReportGenerator\ReportGenerator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ReportGenerator">
      <HintPath>..\ReportGenerator\bin\Release\net10.0\ReportGenerator.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
