<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <Title>Alura Report Generator</Title>
    <Authors>NinoJP</Authors>
    <Version>1.1.0</Version>
    <Description>Biblioteca de geração de relatórios</Description>
    <AssemblyTitle>Alura Report Generator</AssemblyTitle>
    <PackageId>Alura_ReportGenerator</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.6.0" />
    <PackageReference Include="itext.commons" Version="9.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ReportGenerator">
      <HintPath>bin\Release\net10.0\ReportGenerator.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
